apiVersion: v1
kind: Service
metadata:
  name: ark-server
  namespace: ark
  labels:
    run: ark-server
spec:
  type: LoadBalancer
  ports:
  - port: 27018
    protocol: UDP
    name: serverport
    targetPort: 27018
  - port: 7781
    protocol: UDP
    name: steam
    targetPort: 7781
  selector:
    run: ark-server
