apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ark-server
  namespace: ark
spec:
  selector:
    matchLabels:
      run: ark-server
  serviceName: "ark-server"
  replicas: 1
  template:
    metadata:
      labels:
        run: ark-server
    spec:
      containers:
      - name: ark-server
        image: cyrilbkr/ark
        env:
          - name: ADMINPASSWORD
            value: "admin"
          - name: NBPLAYERS
            value: "10"
          - name: SESSIONNAME
            value: "k8s-ark"
          - name: SERVERPASSWORD
            value: ""
          - name: SERVERMAP
            value: "TheIsland"
          - name: TZ
            value: "XX_country"
        ports:
        - containerPort: 27015
          hostPort: 27015
          name: serverport
          protocol: UDP
        - containerPort: 7778
          hostPort: 7778
          name: steam
          protocol: UDP
        - containerPort: 32330
          hostPort: 32330
          name: rcon
        volumeMounts:
        - mountPath: /ark
          name: ark-server
      volumes:
      - name: ark-server
        hostPath:
          path: /data/ark-server
          type: Directory
